### PR TITLE
Added datepicker to datefield

### PR DESCRIPTION
**Pull request by Ewiseman**
I am having a little difficulty getting the **date_field** to format correctly.   For some reason when I integrate **datepicker** it initiates the disabled function in bootstrap.  This means that the **date_field** box is grayed out and when I mouse over it there is circle with a cross through it.  Date picker still works and it still populates to the DB but it doesn't look right.

I did spend some time on Stackoverflow and didn't find anyone else with this error.  Any thoughts?  It is the same in my both applications I am running (Seva and Close_on_time). 

Thanks!

### CODE REVIEW

**Comment by eliotsykes** [comment]
Hey Eric, Sorry I've not been successful trying to get this to happen on a sample app yet. Is there a URL I can take a look at to see the issue?

**Comment by Ewiseman** [comment]
Hi Eliot, 

Here is an example with the mortgage app. 
https://fcfs.herokuapp.com/close-on-time <https://fcfs.herokuapp.com/close-on-time>

Here is an example with the Seva app.  
https://journeyseva.herokuapp.com/ <https://journeyseva.herokuapp.com/>

eric@wisemandv.com <mailto:eric@wisemandv.com>
helloworld

Go to a Journey and try and submit a script.  Use Safari. 

Let me know what you think. 

Thanks!

Eric Wiseman
Ewiseman1@gmail.com
303-909-6990

**Comment by eliotsykes** [comment]
Hey Eric,

I looked at the fcfs example in Chrome and did an "Inspect Element" on the input field to see the CSS for it.

The `input` element has a `readonly` attribute that is setting this cursor style:

```css
cursor: not allowed;
```

Add some CSS for `.form-control` to set the `cursor` to `default`. I believe something like this will do it:

```css
.form-control[readonly] {
  cursor: default;
}
```

Let me know how you get on. Note the information you posted above is publicly viewable on GitHub.

**Comment by Ewiseman** [comment]
Thank you Eliot!

Eric Wiseman
303-909-6990

**Pull request merged**
