### PR TITLE
Redflag on Journey#show & Participant#show

### PR DESCRIPTION
**Pull request by Ewiseman**

### CODE REVIEW

**Comment by Ewiseman** [comment]
Eliot, 

I built out a new feature and ran into an interesting error.  I added some functionality that puts a flag icon in the journey#show page when a checkbox in **welcomescript/_form is selected.  I got everything to work on one participant but when I added another participant it broke and did not recognize my "redflag" method.

```
NoMethodError at /journeys/2
undefined method `redflag' for nil:NilClass
```
Here is the code in question:

```
<td class="text-center"> 
              <% if participant.welcomescript.redflag.present? %>
                <span class="glyphicon glyphicon-flag flag" aria-hidden="true"></span>
              <% end %>
            </td>
```
I assume there is something wrong outside of this path that only occurs when a new participant is created.  If you have any ideas off the top of you head let me know.  Otherwise I can keep plugging away at it.  As always thank you for your help. 

Thanks!

**Comment by Ewiseman** [comment]
I wasn't sure how to proceed with the previous **destroy** error we were working on earlier.  I ended up deleting that branch in order to clean things up locally.  I hope that works for you.  After your last message I continued to try and debug, but something I did changed the URL in Chrome's "View Source"  See below:

```
<a data-method="delete" href="/participants/7/notes/%23%3CNote::ActiveRecord_Associations_CollectionProxy:0x007f932c9e0748%3E" rel="nofollow">Delete</a>
```
It's clear that the note_id is off, but the path is still the same?

```
participant_note_path(@participant, @notes)
```
Based on the Stack trace it looks as tough something is wrong with the **notes_controller**.  Again, through trail and error I've tried every combination path I can think of.  Below is the stack trace

```
Started DELETE "/participants/7/notes/%23%3CNote::ActiveRecord_Associations_CollectionProxy:0x007f932c9e0748%3E" for 127.0.0.1 at 2015-03-06 20:16:42 -0700
Processing by NotesController#destroy as HTML
  Parameters: {"authenticity_token"=>"TX+5HNtmYqMFuXTBVYYHD/kWWhbczO4pEJFZtYFBGbM=", "participant_id"=>"7", "id"=>"#<Note::ActiveRecord_Associations_CollectionProxy:0x007f932c9e0748>"}
Completed 404 Not Found in 2ms

ActiveRecord::RecordNotFound - Couldn't find Journey without an ID:
  activerecord (4.1.8) lib/active_record/relation/finder_methods.rb:411:in `find_with_ids'
  activerecord (4.1.8) lib/active_record/relation/finder_methods.rb:68:in `find'
  activerecord (4.1.8) lib/active_record/querying.rb:3:in `find'
   () Users/ericwiseman/code/Seva/app/controllers/notes_controller.rb:18:in `destroy'
  actionpack (4.1.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.8) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.8) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.8) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.8) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.8) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.8) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
   () Users/ericwiseman/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
   () Users/ericwiseman/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
   () Users/ericwiseman/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```
Let me know your thoughts when you have time.  As always, thank you for all your help!

**Comment by eliotsykes** [comment]
The source of the problem is this link:

```
<a data-method="delete" href="/participants/7/notes/%23%3CNote::ActiveRecord_Associations_CollectionProxy:0x007f932c9e0748%3E" rel="nofollow">Delete</a>
```

The path in the href attribute needs fixing. 

The reason the controller is complaining with an error is because the controller is expecting the URL to contain a note id. The controller may well be fine, the error is with the URL. The URL is generated before the controller gets involved.

Ids in URLs are integers. In this case, the URL path should have this pattern:

```
/participants/:participant_id/notes/:id
```

Examples that match this pattern:

```
/participants/9/notes/4
/participants/123/notes/555
```

This path doesn't match the needed pattern:

```
/participants/7/notes/%23%3CNote::ActiveRecord_Associations_CollectionProxy:0x007f932c9e0748%3E
```

The bit after the final slash in the above path is the result of calling `.inspect` on a **collection** of notes.

Instead of a collection of `Note`s, the URL needs just a single `Note`, which will give just a single id.

```ruby
# @notes is a collection of Note objects, we need it to be a single Note object:
participant_note_path(@participant, @notes)

# More like this:
participant_note_path(@participant, @note)
```

Find the line in the related controller method that is populating the `@notes` object and change it so it populates a single `@note` object.

**Comment by eliotsykes** [comment]
Regarding this error:
```
NoMethodError at /journeys/2 undefined method `redflag' for nil:NilClass
```
This is the important part: **undefined method `redflag' for nil:NilClass**. It means that `.redflag` is being called on `nil`.

In other words, we're calling `.redflag` on a non-existent object (aka `nil`).

Look at the line number and file referenced in the full error stack trace. What is `.redflag` being called on in that line? That's the root of the problem. Something you're expecting to be populated with a model object is `nil` instead.

Let me know how you get on.

With future errors, once you've got as far as you can with debugging, then reach out and include the following information so I've got enough to debug it with:

- Full error message
- Full stack trace
- The stack trace will report a file name and line number. Include this file name and line number in the description/question you send.

**Pull request merged**
