### PR TITLE
email invite test and build

### PR DESCRIPTION
**Pull request by Ewiseman**

### CODE REVIEW

**Comment by Ewiseman** [comment]
Hi Eliot, 

I'm having trouble right off the bat.  I started on line **464** from the notes, ran the specs, and got the predictable error below:

```
Erics-MacBook-Pro:Seva ericwiseman$ rspec spec/features/invite_users_spec.rb 

Invite users
  Invite.send_invite(email)
    enables invited user to register (FAILED - 1)

Failures:

  1) Invite users Invite.send_invite(email) enables invited user to register
     Failure/Error: expect(page).to have_css("h1", text: "Register")
       expected to find css "h1" with text "Register" but there were no matches
     # ./spec/features/invite_users_spec.rb:13:in `block (3 levels) in <top (required)>'

Finished in 0.4431 seconds (files took 2.36 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/invite_users_spec.rb:7 # Invite users Invite.send_invite(email) enables invited user to register
```
I then added 

```html
<h1>Register</h1>
```
 to **app/views/invited_users/new.html.erb** (per the notes). This should satisfied the above failure but it did not, I am still getting the same failure.  It feels like I am missing something simple here. I have been at this for over an hour with no luck.  Any thoughts?

Eric

**Comment by eliotsykes** [comment]
One way to debug this would be to walkthrough the steps we did towards the end of the call and see what happens:

```ruby
# In the Rails console:
Invite.send_invite("x@y.z")
```
```bash
# Read the email that was sent in Terminal:
ls tmp/mails # to see mail files
less tmp/mails/FILE_NAME_HERE_FOR_MAIL

# Then copy the http://localhost:3000/invited_users/new?token=.... URL from the email
# and view it in the browser
```

Following those steps ought to bring you to the same page that the test is failing at. Let me know what you see at that page and if it explains the failure. Send me any error messages you get too.

**Comment by Ewiseman** [comment]
Thanks for getting back to me. That makes sense.  I'll give it a try and let you know how it goes. 

Eric Wiseman

**Comment by Ewiseman** [comment]
Hi Eliot, 

Okay I ran through the debugging steps and was able to open the link in the browser.  The page opens fine, it does show **Register** in h1 formatting, so I cannot figure out why I am still getting this failure:

```
Invite users
  Invite.send_invite(email)
    enables invited user to register (FAILED - 1)

Failures:

  1) Invite users Invite.send_invite(email) enables invited user to register
     Failure/Error: expect(page).to have_css("h1", text: "Register")
       expected to find css "h1" with text "Register" but there were no matches
     # ./spec/features/invite_users_spec.rb:13:in `block (3 levels) in <top (required)>'

Finished in 0.47288 seconds (files took 2.37 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/invite_users_spec.rb:7 # Invite users Invite.send_invite(email) enables invited user to register
```
Thoughts?

**Comment by eliotsykes** [comment]
I'm not sure, but I think the templates might not have the right content...

- Delete the app/views/invited_users/create.html.erb template. This template won't be used. The `create` action is going to redirect.
- Put the <h1>Register</h1> heading in this template: app/views/invited_users/new.html.erb
- Remove the <h1>Register</h1> headings from the `invite.html/text.erb` email template(s) if they have them.

With those changes, does the debugging show anything that helps progress?

**Comment by Ewiseman** [comment]
Well....no luck.  I did all the above.  Everything looks good in the browser and as far as I can tell the ```<h1>Register</h1>``` in the  ``` app/views/invited_users/new.html.erb``` looks good too.  Still getting the same error.  I'll keep at it and let you know if I come up with anything.

**Comment by eliotsykes** [comment]
Tail the test log while the spec runs, it might show an error. In a new terminal window:

```bash
tail -f log/test.log
```

Then run the spec in another terminal.

**Comment by Ewiseman** [comment]
I ran the tail test and did not see any errors.  Not sure what else to do here.  Any chance you have space to look at it before our next call?

**Comment by eliotsykes** [comment]
Hey Eric, yep taking a look this morning, will update when I have something

**Comment by eliotsykes** [comment]
Here's the output from `log/test.log` with added comments, that helped debug the issue:

```
# This is the GET request that happens when the spec clicks the
# "Click here to register" link in the invite email:
Started GET "/invited_users/new?token=cd47eb9df267a0751be4b574290c6157" for 127.0.0.1 at 2015-05-29 09:29:32 +0100
Processing by InvitedUsersController#new as HTML
  Parameters: {"token"=>"cd47eb9df267a0751be4b574290c6157"}

# First clue: "401 Unauthorized" is an HTTP status code (normally expect 
# to see a "200 OK" HTTP status code for a successful request). This says that
# the GET request above is not authorized, meaning a user must be signed in to
# do it. As the user isn't signed in, they're going to get redirected to the 
# sign in page.
Completed 401 Unauthorized in 22ms

# Anonymous user is redirected to sign in page:
Started GET "/users/sign_in" for 127.0.0.1 at 2015-05-29 09:29:33 +0100

Processing by Devise::SessionsController#new as HTML
  Rendered devise/shared/_links.html.erb (1.6ms)
  Rendered devise/sessions/new.html.erb within layouts/application (26.0ms)

Completed 200 OK in 113ms (Views: 109.8ms | ActiveRecord: 0.0ms)
```

The `InvitedUsersController` requires authentication for its actions by default (due to the secure default `before_action :authenticate_user!` in its parent class: `ApplicationController`).

The `new` and `create` actions for `InvitedUsersController` are for users who aren't signed in nor registered, so to fix this, this line can be added to the top of `InvitedUsersController`:

```ruby
class InvitedUsersController < ApplicationController

  skip_before_action :authenticate_user!, only: [:new, :create]
...
end
```

Also changed `new.html.erb` to have the `<h1>Register</h1>` heading.

I've pushed these changes to the `invites` branch on the remote repo, so you can pull them to yours.

After incorporating these changes, the next time you run the spec, I expect you'll see the same failure I am:

```
  1) Invite users Invite.send_invite(email) enables invited user to register
     Failure/Error: fill_in "Choose a password", with: "some password"
     Capybara::ElementNotFound:
       Unable to find field "Choose a password"
     # ./spec/features/invite_users_spec.rb:14:in `block (3 levels) in <top (required)>'
```

**Comment by eliotsykes** [comment]
PS. Take a look at the other 2 or 3 commits I added to the `invites` branch and review their changes and read the commit messages. If you've got any questions on them please ask away! :+1:

**Pull request merged**
